---
-
  hosts: dev
  user: ansible
  become: true
  tasks:
    - name: Prompt user to verify before continue
      pause:
        prompt: Please check that the webserver is running, press enter to continue
