---
-
  hosts: all
  user: ansible
  become: true
  vars:
    jobids: []
  tasks:
    - name: Task 1
      command: /bin/sleep 5
      when: ansible_hostname == 'ip-172-31-9-29'
      async: 10
      poll: 0
      register: result1

    - name: Task 2
      command: /bin/sleep 5
      when: ansible_hostname == 'ip-172-31-3-48'
      async: 10
      poll: 0
      register: result2
	  
    - name: Task 3
      command: /bin/sleep 5
      when: ansible_hostname == 'ip-172-31-1-171'
      async: 10
      poll: 0
      register: result3

    - name: Show registered context
      debug:
        var: result1

    - name: Capture Job IDs
      set_fact:
        jobids: >
                {% if item.ansible_job_id is defined -%}
                  {{ jobids + [item.ansible_job_id] }}
                {% else -%}
                  {{ jobids }}
                {% endif %}
      with_items: "{{ [ result1, result2, result3 ] }}"

    - name: Show Job IDs
      debug:
        var: jobids
