---
-
  hosts: all
  user: ansible
  become: true
  tasks:
    - name: Exploring register
      command: hostname -s
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution_major_version | int >= 7
      register: command_register

    - name: Install patch when changed
      yum:
        name: patch
        state: present
      when: command_register.changed
