---
-
  hosts: ubuntu
  user: ansible
  become: true
  tasks:
    - name: Create random directory
      file:
        dest: "/home/james/{{ item }}"
        state: directory
      with_random_choice:
        - "aws"
        - "azure"
        - "gcp"
        - "ibm"
