---
-
  hosts: ubuntu
  user: ansible
  become: true
  tasks:
    - name: Create authorized key
      authorized_key:
        user: lakshmi
        key: "{{ item }}"
      with_file:
        - /home/ansible/.ssh/id_rsa.pub
        - custom_key.pub
